### ISSUE TITLE
Can i add other programs like sorting etc in c or java?

### ISSUE THREAD

**Issue by ItsMeVikashKumarSingh** [Harshil525/Hello-World-in-Multiple-Languages#21]
Can i add other programs like sorting etc in c or java?

**Comment by Harshil525** [comment]
No, this is for hello World basics in all the languages.
For those kinds of issues, you can refer to https://github.com/20sinkypriya/Leetcoding , this is also related to Hacktoberfest. You can create issues and PRs over there.
